package com.example.intents_foregroundservicemytest.Const

object Const {

    const val CHANEL_FOR_FOREGROUND_SERVICE = "CHANEL_FOR_FOREGROUND_SERVICE"
    const val CHANEL_FOR_FOREGROUND_SERVICE_ID = 1

    const val CHANEL_FOR_TEST_FOREGROUND_SERVICE = "CHANEL_FOR_TEST_FOREGROUND_SERVICE"
    const val CHANEL_FOR_TEST_FOREGROUND_SERVICE_ID = 2


    const val CHANEL_FOR_TEST_FOREGROUND_SERVICE_WITHOUT_APP_INSTANCE = "CHANEL_FOR_TEST_FOREGROUND_SERVICE_WITHOUT_APP_INSTANCE"
    const val CHANEL_FOR_TEST_FOREGROUND_SERVICE_WITHOUT_APP_INSTANCE_ID = 3

}